# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 840)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 840))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 840))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setMinimumSize(QtCore.QSize(1, 1))
        self.image_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.image_label.setMouseTracking(False)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.image_label.setObjectName("image_label")
        self.verticalLayout.addWidget(self.image_label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuSource = QtWidgets.QMenu(self.menubar)
        self.menuSource.setObjectName("menuSource")
        self.menuSensor = QtWidgets.QMenu(self.menubar)
        self.menuSensor.setObjectName("menuSensor")
        self.menuAWS = QtWidgets.QMenu(self.menuSensor)
        self.menuAWS.setObjectName("menuAWS")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSelect_notation_unit = QtWidgets.QMenu(self.menuView)
        self.menuSelect_notation_unit.setObjectName("menuSelect_notation_unit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImage_File = QtWidgets.QAction(MainWindow)
        self.actionImage_File.setObjectName("actionImage_File")
        self.actionCamera_1 = QtWidgets.QAction(MainWindow)
        self.actionCamera_1.setObjectName("actionCamera_1")
        self.actionCamera_2 = QtWidgets.QAction(MainWindow)
        self.actionCamera_2.setObjectName("actionCamera_2")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCamera_3 = QtWidgets.QAction(MainWindow)
        self.actionCamera_3.setObjectName("actionCamera_3")
        self.actionON = QtWidgets.QAction(MainWindow)
        self.actionON.setCheckable(True)
        self.actionON.setObjectName("actionON")
        self.actionOFF = QtWidgets.QAction(MainWindow)
        self.actionOFF.setObjectName("actionOFF")
        self.actionTarget_ON = QtWidgets.QAction(MainWindow)
        self.actionTarget_ON.setObjectName("actionTarget_ON")
        self.actionTarget_OFF = QtWidgets.QAction(MainWindow)
        self.actionTarget_OFF.setObjectName("actionTarget_OFF")
        self.actionPolar_Plot = QtWidgets.QAction(MainWindow)
        self.actionPolar_Plot.setObjectName("actionPolar_Plot")
        self.actionkm = QtWidgets.QAction(MainWindow)
        self.actionkm.setCheckable(True)
        self.actionkm.setChecked(True)
        self.actionkm.setObjectName("actionkm")
        self.actionmi = QtWidgets.QAction(MainWindow)
        self.actionmi.setCheckable(True)
        self.actionmi.setObjectName("actionmi")
        self.menuSource.addAction(self.actionImage_File)
        self.menuSource.addAction(self.actionCamera_1)
        self.menuSource.addAction(self.actionCamera_2)
        self.menuSource.addAction(self.actionCamera_3)
        self.menuSource.addAction(self.actionExit)
        self.menuAWS.addSeparator()
        self.menuAWS.addAction(self.actionON)
        self.menuSensor.addAction(self.menuAWS.menuAction())
        self.menuMode.addAction(self.actionTarget_ON)
        self.menuMode.addAction(self.actionTarget_OFF)
        self.menuSelect_notation_unit.addAction(self.actionkm)
        self.menuSelect_notation_unit.addAction(self.actionmi)
        self.menuView.addAction(self.actionPolar_Plot)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuSelect_notation_unit.menuAction())
        self.menubar.addAction(self.menuSource.menuAction())
        self.menubar.addAction(self.menuSensor.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JS-06"))
        self.menuSource.setTitle(_translate("MainWindow", "File"))
        self.menuSensor.setTitle(_translate("MainWindow", "Sensor"))
        self.menuAWS.setTitle(_translate("MainWindow", "AWS"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSelect_notation_unit.setTitle(_translate("MainWindow", "Distance unit"))
        self.actionImage_File.setText(_translate("MainWindow", "Image File"))
        self.actionImage_File.setStatusTip(_translate("MainWindow", "Open an image file"))
        self.actionCamera_1.setText(_translate("MainWindow", "Camera 1"))
        self.actionCamera_1.setStatusTip(_translate("MainWindow", "Get video from webcam"))
        self.actionCamera_2.setText(_translate("MainWindow", "Camera 2"))
        self.actionCamera_2.setStatusTip(_translate("MainWindow", "Get video from Hanwha PNM-9030V"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit JS-06"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionCamera_3.setText(_translate("MainWindow", "Camera 3"))
        self.actionCamera_3.setStatusTip(_translate("MainWindow", "Get video from Hanwha XNO-8080R"))
        self.actionON.setText(_translate("MainWindow", "ON"))
        self.actionOFF.setText(_translate("MainWindow", "OFF"))
        self.actionTarget_ON.setText(_translate("MainWindow", "Target_ON"))
        self.actionTarget_OFF.setText(_translate("MainWindow", "Target_OFF"))
        self.actionPolar_Plot.setText(_translate("MainWindow", "Polar Plot"))
        self.actionkm.setText(_translate("MainWindow", "km"))
        self.actionmi.setText(_translate("MainWindow", "mi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

